version: 1.0
name: DrizzardKits
author: Infectings
main: com.drizzard.main
description: A GUI for the command /kit
softdepend: [Essentials,EssentialsX]
commands:
    kit: 
      description: Essentials /kit with gui
      usage: /kit
    kitcfg: 
      description: Configurations for /kit GUI
      usage: /kitcfg
